<?php // this is an autogenerated file - do not edit (created Thu, 10 Feb 2011 22:43:19 +0100)
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'theseer\\phpdox\\builder' => '/src/builder.php',
            'theseer\\phpdox\\classbuilder' => '/src/classbuilder.php',
            'theseer\\phpdox\\cli' => '/src/cli.php',
            'theseer\\phpdox\\cliexception' => '/src/cli.php',
            'theseer\\phpdox\\collector' => '/src/collector.php',
            'theseer\\phpdox\\docblock' => '/src/docblock.php',
            'theseer\\phpdox\\generator' => '/src/generator.php',
            'theseer\\phpdox\\generatorexception' => '/src/generator.php',
            'theseer\\phpdox\\genericbackend' => '/src/backend/genericbackend.php',
            'theseer\\phpdox\\htmlbuilder' => '/src/backend/htmlbuilder.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
