#!/usr/bin/env php
<?php
/*
 * Copyright (c) 2010-2017 Arne Blankerts <arne@blankerts.de>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 *   * Redistributions of source code must retain the above copyright notice,
 *     this list of conditions and the following disclaimer.
 *
 *   * Redistributions in binary form must reproduce the above copyright notice,
 *     this list of conditions and the following disclaimer in the documentation
 *     and/or other materials provided with the distribution.
 *
 *   * Neither the name of Arne Blankerts nor the names of contributors
 *     may be used to endorse or promote products derived from this software
 *     without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT  * NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER ORCONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * @package    phpDox
 * @author     Arne Blankerts <arne@blankerts.de>
 * @copyright  Arne Blankerts <arne@blankerts.de>, All rights reserved.
 * @license    BSD License
 * @exitcodes  0 No error
 *             1 Execution Error
 *             3 Parameter Error
 *
 */

if (!defined('HHVM_VERSION') && (version_compare(phpversion(), '5.5', 'lt'))) {
    fwrite(
        STDERR,
        sprintf(
            "phpDox requires PHP 5.5 or later; " .
            "Upgrading to the latest version of PHP is highly recommended. (Version used: %s)\n\n",
            phpversion()
        )
    );

    die(1);
}

require __DIR__ . '/src/autoload.php';

$found = false;
foreach(array(__DIR__ . '/vendor', __DIR__ . '/../..') as $vendor) {
    if (file_exists($vendor . '/autoload.php')) {
        $found = true;
        require $vendor . '/autoload.php';
        break;
    }
}

if (!$found) {
    fwrite(STDERR,
        "The vendor directory was not found at the expected locations.\nDid you run composer install?\n\n"
    );
    exit(1);
}

$factory = new TheSeer\phpDox\Factory(
    new \TheSeer\phpDox\FileInfo(__DIR__),
    new \TheSeer\phpDox\Version('0.11.0-dev')
);
exit($factory->getCLI()->run(
    new TheSeer\phpDox\CLIOptions($_SERVER['argv'])
));
