<?php // this is an autogenerated file - do not edit (created Wed, 29 Sep 2010 00:27:16 +0200)
spl_autoload_register(
   function($class) {
      static $classes = array(
         'theseer\\phpdox\\parser' => '/parser.php',
         'theseer\\phpdox\\stackhandlerfactory' => '/stackhandler.php',
         'theseer\\phpdox\\stackhandler' => '/stackhandler.php',
         'theseer\\phpdox\\classstackhandler' => '/classhandler.php',
         'theseer\\phpdox\\functionstackhandler' => '/functionhandler.php',
         'theseer\\phpdox\\namespacestackhandler' => '/namespacehandler.php',
         'theseer\\phpdox\\debugstackhandler' => '/debughandler.php',
         'theseer\\phpdox\\processcontext' => '/processcontext.php',
         'theseer\\phpdox\\processcontextexception' => '/processcontext.php',
         'theseer\\phpdox\\variablestackhandler' => '/variablehandler.php',
         'theseer\\phpdox\\conststackhandler' => '/consthandler.php',
         'theseer\\phpdox\\interfacestackhandler' => '/interfacehandler.php',
         'theseer\\phpdox\\valuehandler' => '/valuehandler.php'
      );
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
