<?php // this is an autogenerated file - do not edit (created Fri, 11 Mar 2011 16:39:39 +0100)
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'theseer\\phpdox\\application' => '/application.php',
            'theseer\\phpdox\\builder' => '/builder.php',
            'theseer\\phpdox\\classbuilder' => '/classbuilder.php',
            'theseer\\phpdox\\cli' => '/cli.php',
            'theseer\\phpdox\\cliexception' => '/cli.php',
            'theseer\\phpdox\\collector' => '/collector.php',
            'theseer\\phpdox\\docblock' => '/docblock.php',
            'theseer\\phpdox\\generator' => '/generator.php',
            'theseer\\phpdox\\generatorexception' => '/generator.php',
            'theseer\\phpdox\\genericbackend' => '/backend/genericbackend.php',
            'theseer\\phpdox\\htmlbuilder' => '/backend/htmlbuilder.php',
            'theseer\\phpdox\\progresslogger' => '/logger/progresslogger.php',
            'theseer\\phpdox\\progressloggerexception' => '/logger/progresslogger.php',
            'theseer\\phpdox\\shellprogresslogger' => '/logger/shellprogresslogger.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
